// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ6Ljtg-sJ6QDiZdEozsP3Ci6kb_IHgIY',
    appId: '1:887472697490:android:95231faecc49e0a8a7364b',
    messagingSenderId: '887472697490',
    projectId: 'taxiapp-6d76e',
    storageBucket: 'taxiapp-6d76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldvtVsE7YHL588xch93pJDgxTdtM9wjo',
    appId: '1:887472697490:ios:f56c65b943a3bfe9a7364b',
    messagingSenderId: '887472697490',
    projectId: 'taxiapp-6d76e',
    storageBucket: 'taxiapp-6d76e.appspot.com',
    iosBundleId: 'com.example.taxiapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbL3de_FG7CEkveO_Gsi8EA9M8VvL3RG0',
    appId: '1:887472697490:web:00593c8550ea00b4a7364b',
    messagingSenderId: '887472697490',
    projectId: 'taxiapp-6d76e',
    authDomain: 'taxiapp-6d76e.firebaseapp.com',
    storageBucket: 'taxiapp-6d76e.appspot.com',
    measurementId: 'G-B6K2YHETLV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAldvtVsE7YHL588xch93pJDgxTdtM9wjo',
    appId: '1:887472697490:ios:f56c65b943a3bfe9a7364b',
    messagingSenderId: '887472697490',
    projectId: 'taxiapp-6d76e',
    storageBucket: 'taxiapp-6d76e.appspot.com',
    iosBundleId: 'com.example.taxiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbL3de_FG7CEkveO_Gsi8EA9M8VvL3RG0',
    appId: '1:887472697490:web:a7e80a44389695dba7364b',
    messagingSenderId: '887472697490',
    projectId: 'taxiapp-6d76e',
    authDomain: 'taxiapp-6d76e.firebaseapp.com',
    storageBucket: 'taxiapp-6d76e.appspot.com',
    measurementId: 'G-YWW4321HN6',
  );

}